info:
  profile: prod

name: Paul
words: 'God bless you, my bady!'
#对称加密
# food: '{cipher}326433bb02af1991beecf1b29f9d1d224d4f8241722e8a553cfa7077905bfdfc'
food: '326433bb02af1991beecf1b29f9d1d224d4f8241722e8a553cfa7077905bfdfc'
#非对称加密
delicious: '{cipher}AQAy6mX/UvvLVCq90XhIKQqC2ibbibOn+OCGW/1ivXdeVgdlC4FhIDQS9SJr1n5e/wa2b5KMzOpz3eRCe6CQuuHtVISUaD9yO4R03pW4DDdAwGafrNssZ86geao/AOwEafyaPYH0yAa/bckotghK+SzrMV5tyxz3D5faYyapSrlgPT4COU2F5wRVf9ogiaTsSvI85Ft7AD/mCLotmaSRC0IgYW5KHIouYUNE3EuoQ+5BRBLN85MalZJVLnU2IP9VUUzL+/8o7HL5b0+UZf/7ZIcuGNYFdJpryvY0OPIvtxL1tO0Hp2QGNlcrjGHFT0hEl/L0uZqMRBAm3fapdpBN3Ghzrz7Syv9bNnN8H1+pTYmt1Ure9joKT7mIb3+uMQltyjo='
